### ISSUE TITLE
It's not working, because without wrap by <form>

### ISSUE THREAD

**Issue by rwecho** [ndom91/next-auth-example-sign-in-page#1]
The current code without <form> and callback and error handling.
so the repo is not working.

**Comment by ndom91** [comment]
Have you tried the demo application (https://next-auth-example-sign-in-page.vercel.app/auth/signin)? OAuth (Github) login works for me. 

Are you trying to use a different type of provider?

**Comment by rwecho** [comment]
it works.
I mean when accessing an unauthorized page, it redirects to Singin.tsx with the callback.
I think the repo is not for that?

**Comment by ndom91** [comment]
Correct, the repo is simply for showing the custom sign-in page as an example.

Going to close this then :+1:
